# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [5]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [6]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.95416315 0.89251597 0.51635848 ... 0.92427778 0.46484556 0.41108898]
 [0.74684435 0.93125321 0.42374369 ... 0.88225779 0.01078943 0.25846558]
 [0.36610525 0.60423197 0.92148954 ... 0.47044757 0.60566531 0.67605414]
 ...
 [0.04390347 0.53085947 0.70287332 ... 0.86543369 0.01520036 0.01020305]
 [0.08120663 0.8034208  0.81114932 ... 0.62449121 0.97382487 0.36181339]
 [0.34929409 0.42124221 0.20067965 ... 0.33199146 0.19544355 0.16438009]]
[[0.08262989 0.01370027 0.19602092 ... 0.44038774 0.78054062 0.79335346]
 [0.62288165 0.89534703 0.28779493 ... 0.19369788 0.98489626 0.67572044]
 [0.97582064 0.02967375 0.53910283 ... 0.86747473 0.23418069 0.92458309]
 ...
 [0.86627888 0.55350669 0.43855705 ... 0.34327892 0.92420793 0.94442314]
 [0.4633774  0.01106874 0.14094197 ... 0.45203872 0.65549294 0.72552365]
 [0.85231881 0.26279148 0.52517248 ... 0.54827802 0.27946991 0.94236902]]


Без использования numpy

In [7]:
def mult(a, b):
    result = []
    for i in range(len(a)):
        row = []
        for j in range(len(b[0])):
            val = sum(a[i][k] * b[k][j] for k in range(len(b)))
            row.append(val)
        result.append(row)
    return result

C использованием numpy

In [8]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [9]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 752 ms, sys: 386 µs, total: 752 ms
Wall time: 759 ms


In [10]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.79 ms, sys: 93 µs, total: 1.89 ms
Wall time: 2.49 ms


In [11]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.517364012215694e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [12]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.3898395  0.19142698 0.41633783] [0.9051006  0.09695105 0.80164626]


In [15]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [16]:


def np_scalar_product(a,b):
    return np.dot(a, b)



In [17]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 16 µs, sys: 2 µs, total: 18 µs
Wall time: 21.9 µs
CPU times: user 753 µs, sys: 971 µs, total: 1.72 ms
Wall time: 1.75 ms


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Потому что numpy написан на C и заранее скомпилирован, что дает преимущество на интерпретируемыми операциями Python

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [19]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    d = np.diag(a)
    diag = d[d % 2 == 0]
    if len(diag) == 0:
        return 0
    else:
        return np.sum(diag)

In [20]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[2, 9, 2, 8, 3],
       [9, 7, 8, 6, 7],
       [9, 2, 3, 5, 2],
       [2, 7, 2, 5, 6],
       [1, 1, 8, 3, 1]])

In [21]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 140 µs, sys: 19 µs, total: 159 µs
Wall time: 165 µs


2

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [23]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    _sum = np.cumsum(X, axis=1)
    indices = np.arange(1, X.shape[1] + 1)
    result = _sum / indices[:, np.newaxis]
    return result

In [24]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[9.32903520e-01 3.53912936e-01 2.37927136e-01 2.06902058e-01
 5.26931609e-01 4.66049803e-01 6.65973017e-01 9.18149944e-01
 9.15789040e-01 7.17213858e-01 4.10365455e-01 2.00542425e-01
 2.48052712e-01 2.89021910e-01 4.10476581e-01 7.77814574e-01
 2.50179370e-01 5.93931451e-01 6.71731076e-01 7.92260062e-02
 7.01997572e-01 4.41879127e-01 3.75432543e-01 8.10476897e-01
 8.16847249e-01 1.57337229e-02 6.04864243e-01 6.85302958e-01
 2.07958920e-01 4.33751282e-01 5.15867462e-01 8.44311053e-01
 9.24885694e-01 7.91425585e-01 9.17689177e-01 6.34992259e-01
 4.38287710e-01 6.70803522e-01 5.88935849e-01 6.11434171e-01
 9.94213700e-01 2.67604107e-01 4.35506818e-01 1.83158823e-01
 8.92708021e-01 2.41421319e-01 7.84028142e-01 5.49206214e-01
 5.72062196e-01 6.92383891e-01 3.80085848e-01 7.63652146e-01
 5.00716757e-01 3.70147568e-01 4.50465528e-01 1.56533724e-01
 5.15364629e-01 8.69603347e-01 1.50761719e-02 7.03814974e-01
 5.28338352e-01 1.09303285e-01 9.85886591e-01 8.87915107e-01
 6.16531396e-01 5.219535

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [27]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):

    res = []
    c = 1

    for i in range(1, len(a)):
        if a[i] == a[i-1]:  c += 1
        else:
            res.append(a[i-1])
            res.append(c)
            c = 1

    res.append(a[-1])
    res.append(c)

    return np.array(res[0::2]), np.array(res[1::2])

In [28]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 57 µs, sys: 0 ns, total: 57 µs
Wall time: 61.3 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [29]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    _X = np.copy(X)
    _X[1::2] = a
    _X[::2] = np.power(_X[::2], 3)
    result = np.concatenate((X, _X[::-1]))
    return result

In [30]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 132 µs, sys: 18 µs, total: 150 µs
Wall time: 212 µs
